# Generated by Django 5.1.1 on 2025-10-01 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv projekta')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Broj ugovora')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Datum ugovora')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Vrijednost ugovora (EUR)')),
                ('start_date', models.DateField(verbose_name='Datum početka')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Datum završetka')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customers.customer', verbose_name='Kupac')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekti',
                'ordering': ['-created_at'],
            },
        ),
    ]
