# Generated by Django 5.1.1 on 2025-10-01 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Broj naloga')),
                ('title', models.CharField(max_length=200, verbose_name='Naziv naloga')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('approved', 'Odobren'), ('in_progress', 'U tijeku'), ('completed', 'Završen'), ('cancelled', 'Otkazan')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Planirani datum')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Datum završetka')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Radni nalog',
                'verbose_name_plural': 'Radni nalozi',
                'ordering': ['-created_at'],
            },
        ),
    ]
