# Generated by Django 5.1.1 on 2025-10-01 09:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('projects', '0002_workorder'),
        ('roads', '0003_length_trigger_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_side', models.CharField(choices=[('right', 'Desna'), ('left', 'Lijeva'), ('notap', 'Nije primjenjivo')], help_text='Lijeva, Desna ili prazno', max_length=5, verbose_name='Strana ceste')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3765, verbose_name='Geometrija (izvedeni poligon)')),
                ('description', models.TextField(blank=True, verbose_name='Opis stavke')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Količina')),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Jedinična cijena')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Ukupna cijena')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('comparation', models.CharField(blank=True, max_length=20, verbose_name='Usporedba')),
                ('comparation_subject', models.CharField(blank=True, choices=[('project', 'Projekt'), ('road_section', 'Dionica'), ('operation', 'Operacija')], help_text='Odaberite subjekt usporedbe', max_length=20, verbose_name='Subjekt usporedbe')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.operationtype', verbose_name='Vrsta operacije')),
                ('road_section', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='roads.roadsection', verbose_name='Dionica ceste')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='projects.workorder', verbose_name='Radni nalog')),
            ],
            options={
                'verbose_name': 'Stavka rada',
                'verbose_name_plural': 'Stavke rada',
                'ordering': ['work_order', 'id'],
            },
        ),
    ]
