# Generated by Django 5.1.1 on 2025-10-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_workitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='comparation',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='comparation_subject',
        ),
    ]
