# Generated by Django 5.1.1 on 2025-10-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_workitem_comparation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Jedinična cijena'),
        ),
    ]
