services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-road_maintenance.settings}
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    networks:
      - dell_network
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

networks:
  dell_network:
    external: true
