# Generated by Django 5.1.1 on 2025-10-01 04:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv dionice')),
                ('road_number', models.CharField(blank=True, max_length=50, verbose_name='Broj ceste')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=3765, verbose_name='Geometrija')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Duljina (m)')),
                ('road_width', models.DecimalField(blank=True, decimal_places=2, help_text='Prosječna širina kolnika u metrima.', max_digits=5, null=True, verbose_name='Širina ceste (m)')),
                ('description', models.TextField(blank=True, verbose_name='Opis dionice')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja')),
            ],
            options={
                'verbose_name': 'Dionica ceste',
                'verbose_name_plural': 'Dionice cesta',
                'ordering': ['name'],
            },
        ),
    ]
