# Generated by Django 5.1.1 on 2025-10-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsection',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Duljina (m)'),
        ),
    ]
