# Generated by Django 5.1.1 on 2025-10-01 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_form', models.CharField(blank=True, choices=[('d.o.o.', 'd.o.o.'), ('j.d.o.o.', 'j.d.o.o.'), ('obrt', 'Obrt'), ('u.o.', 'Udruga'), ('d.d.', 'd.d.'), ('ostalo', 'Ostalo')], help_text='Pravna forma (npr. d.o.o., j.d.o.o.).', max_length=16)),
                ('oib', models.CharField(help_text='Hrvatski OIB (11 znamenki).', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^\\d{11}$', 'OIB mora sadržavati točno 11 znamenki.')])),
                ('mbs', models.CharField(blank=True, help_text='Matični broj subjekta (MBS) iz sudskog registra.', max_length=50, verbose_name='MBS')),
                ('vat_registered', models.BooleanField(default=True, help_text='Označuje je li subjekt u sustavu PDV-a.')),
                ('vat_id', models.CharField(blank=True, help_text='Europski PDV identifikacijski broj (npr. HR12345678901).', max_length=32, verbose_name='VAT ID')),
                ('street_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Poštanski broj mora imati 5 znamenki.')])),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, help_text='Županija u kojoj je sjedište klijenta.', max_length=100)),
                ('country', models.CharField(default='Croatia', max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_mobile', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, help_text='Primarni IBAN za transakcije.', max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{15,34}$', 'IBAN smije sadržavati samo velika slova i znamenke (15-34 znakova).')])),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('swift_bic', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{8}(?:[A-Z0-9]{3})?$', 'Neispravan SWIFT/BIC format.')])),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30, help_text='Standardni broj dana za plaćanje računa.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
