# Generated by Django 5.1.1 on 2025-10-01 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Kupac', 'verbose_name_plural': 'Kupci'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banka'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kontakt e-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mobilni telefon'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kontakt osoba'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Hrvatska', max_length=100, verbose_name='Država'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.CharField(blank=True, help_text='Županija u kojoj je sjedište klijenta.', max_length=100, verbose_name='Županija'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='iban',
            field=models.CharField(blank=True, help_text='Primarni IBAN za transakcije.', max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{15,34}$', 'IBAN smije sadržavati samo velika slova i znamenke (15-34 znakova).')], verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('d.o.o.', 'd.o.o.'), ('j.d.o.o.', 'j.d.o.o.'), ('obrt', 'Obrt'), ('u.o.', 'Udruga'), ('d.d.', 'd.d.'), ('ostalo', 'Ostalo')], help_text='Pravna forma (npr. d.o.o., j.d.o.o.).', max_length=16, verbose_name='Pravna forma'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Bilješke'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='oib',
            field=models.CharField(help_text='Hrvatski OIB (11 znamenki).', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^\\d{11}$', 'OIB mora sadržavati točno 11 znamenki.')], verbose_name='OIB'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Standardni broj dana za plaćanje računa.', verbose_name='Rok plaćanja (dani)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Poštanski broj mora imati 5 znamenki.')], verbose_name='Poštanski broj'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_address',
            field=models.CharField(max_length=255, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='swift_bic',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{8}(?:[A-Z0-9]{3})?$', 'Neispravan SWIFT/BIC format.')], verbose_name='SWIFT/BIC'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_id',
            field=models.CharField(blank=True, help_text='Europski PDV identifikacijski broj (npr. HR12345678901).', max_length=32, verbose_name='PDV ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_registered',
            field=models.BooleanField(default=True, help_text='Označuje je li subjekt u sustavu PDV-a.', verbose_name='U sustavu PDV-a'),
        ),
    ]
