# Generated by Django 5.1.1 on 2025-10-01 10:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Korisničko ime iz pokušaja prijave.', max_length=150, verbose_name='Korisničko ime')),
                ('action', models.CharField(choices=[('login', 'Prijava'), ('logout', 'Odjava'), ('failure', 'Neuspjela prijava')], max_length=16, verbose_name='Radnja')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Vrijeme')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa')),
                ('user_agent', models.TextField(blank=True, verbose_name='Korisnički agent')),
                ('path', models.CharField(blank=True, max_length=512, verbose_name='URL')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name': 'Evidencija prijave',
                'verbose_name_plural': 'Evidencije prijava',
                'ordering': ['-timestamp'],
            },
        ),
    ]
