# Generated by Django 5.1.1 on 2025-10-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv operacije')),
                ('description', models.TextField(blank=True, verbose_name='Opis rada')),
                ('unit', models.CharField(choices=[('m2', 'm²'), ('m3', 'm³'), ('m', 'm'), ('kom', 'komad'), ('kg', 'kilogram'), ('sat', 'sat'), ('dan', 'dan'), ('pšj', 'paušalno')], max_length=10, verbose_name='Jedinica mjere')),
                ('base_price', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Osnovna cijena')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
            ],
            options={
                'verbose_name': 'Vrsta operacije',
                'verbose_name_plural': 'Vrste operacija',
                'ordering': ['name'],
            },
        ),
    ]
