# Generated by Django 5.1.1 on 2025-10-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_alter_workitem_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Verzija pregleda')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('pending_review', 'Čeka kupca'), ('accepted', 'Prihvaćeno'), ('change_requested', 'Tražena dorada'), ('expired', 'Isteklo'), ('cancelled', 'Otkazano')], db_index=True, default='draft', max_length=32, verbose_name='Status pregleda')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Rok za odgovor kupca')),
                ('note_public', models.TextField(blank=True, help_text='Kratka napomena koja se prikazuje kupcu u emailu/na stranici.', verbose_name='Poruka kupcu')),
                ('data_snapshot_hash', models.CharField(blank=True, help_text='Kriptografski hash payload-a prikazanog kupcu u ovoj verziji.', max_length=128, verbose_name='Hash prikazanih podataka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zaključano')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='projects.workitem', verbose_name='Stavka posla (WorkItem)')),
            ],
            options={
                'verbose_name': 'Pregled kupca (CustomerReview)',
                'verbose_name_plural': 'Pregledi kupaca (CustomerReviews)',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['work_item', 'version'], name='customer_re_work_it_eba7f5_idx'), models.Index(fields=['status'], name='customer_re_status_5c96ed_idx')],
                'unique_together': {('work_item', 'version')},
            },
        ),
    ]
