# Generated by Django 5.1.1 on 2025-10-01 12:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accepted', 'Prihvaćeno'), ('change_requested', 'Tražena dorada')], db_index=True, max_length=32, verbose_name='Akcija')),
                ('comment', models.TextField(blank=True, help_text="Obavezno za 'Tražena dorada'.", verbose_name='Komentar')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Opcionalno; označite područje na mapi gdje rad nije zadovoljavajući.', null=True, srid=3765, verbose_name='Geometrija prigovora (point/polygon)')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Opcionalno; metapodaci/URL-ovi dokumenata/fotografija.', verbose_name='Privitci (JSON)')),
                ('data_snapshot_hash', models.CharField(blank=True, help_text='Hash payload-a prikazanog kupcu u trenutku odluke.', max_length=128, verbose_name='Hash prikazanih podataka')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='Vrijeme odluke')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('customer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='customer_review.customerreview', verbose_name='Runda pregleda (CustomerReview)')),
                ('decided_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_review_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Kupac (korisnik koji je odlučio)')),
            ],
            options={
                'verbose_name': 'Odluka kupca (CustomerReviewDecision)',
                'verbose_name_plural': 'Odluke kupaca (CustomerReviewDecisions)',
                'ordering': ('-decided_at',),
                'indexes': [models.Index(fields=['customer_review', 'action'], name='customer_re_custome_67cb5d_idx'), models.Index(fields=['decided_at'], name='customer_re_decided_902dcb_idx')],
                'unique_together': {('customer_review', 'decided_by_user')},
            },
        ),
    ]
