# Generated by Django 5.1.1 on 2025-10-01 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_review', '0002_customerreviewdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(editable=False, help_text='Jedinstveni token koji ide u URL.', max_length=200, unique=True, verbose_name='Token (jti)')),
                ('scope', models.CharField(default='workitem:review', help_text='Logički opseg upotrebe tokena.', max_length=64, verbose_name='Opseg (scope)')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Vrijeme izdavanja')),
                ('expires_at', models.DateTimeField(verbose_name='Vrijedi do')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Iskorišten u')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Opozvan u')),
                ('delivered_to_email', models.EmailField(blank=True, max_length=254, verbose_name='Poslano na email')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Npr. kanal slanja, IP/UA prvog otvaranja i sl.', verbose_name='Meta')),
                ('customer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='customer_review.customerreview', verbose_name='Runda pregleda (CustomerReview)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Kupac (primatelj tokena)')),
            ],
            options={
                'verbose_name': 'Review token',
                'verbose_name_plural': 'Review tokeni',
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['customer_review', 'user'], name='customer_re_custome_101d77_idx'), models.Index(fields=['expires_at'], name='customer_re_expires_d01d94_idx'), models.Index(fields=['revoked_at', 'used_at'], name='customer_re_revoked_5180d3_idx')],
            },
        ),
    ]
