# Generated by Django 5.1.1 on 2025-10-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_review', '0003_reviewtoken'),
        ('projects', '0005_alter_workitem_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreview',
            options={'ordering': ('-created_at',), 'verbose_name': 'Pregled kupca', 'verbose_name_plural': 'Pregledi kupaca'},
        ),
        migrations.AlterModelOptions(
            name='customerreviewdecision',
            options={'ordering': ('-decided_at',), 'verbose_name': 'Odluka kupca', 'verbose_name_plural': 'Odluke kupaca'},
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='projects.workitem', verbose_name='Stavka posla'),
        ),
        migrations.AlterField(
            model_name='customerreviewdecision',
            name='customer_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='customer_review.customerreview', verbose_name='Runda pregleda'),
        ),
    ]
